apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-users
data:
  tomcat-users.xml: |
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users>
      <role rolename="manager-gui"/>
      <role rolename="admin-gui"/>
      <user username="user-example" password="password-example" roles="manager-gui,admin-gui"/>
    </tomcat-users>