apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: example
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
