apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv
  namespace: example
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/tomcat
